# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-03-06 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hour',
            name='requested_date',
            field=models.DateTimeField(verbose_name='YYYY-MM-DD HH:MM'),
        ),
    ]
