# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-01-07 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0002_auto_20200107_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hour',
            old_name='order_id',
            new_name='order',
        ),
    ]
