# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-01-08 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0004_auto_20200107_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hour',
            name='comments',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='hour',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
