# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-29 09:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.TextField(max_length=500)),
                ('upvotes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('comment_number', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('To do', 'To do'), ('In progress', 'In progress'), ('Done', 'Done'), ('Cancelled', 'Cancelled')], default='To do', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PServices_Bought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=256)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('ProfService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfessionalServices.PServices')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
