# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-04 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.TextField(max_length=500)),
                ('purchases', models.IntegerField(default=0)),
                ('udPrice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('totalHours', models.DecimalField(decimal_places=0, max_digits=5)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Current Unavailable', 'Current Unavailable')], default='Available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PServices_Bought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=256)),
                ('udPrice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('totalHours', models.DecimalField(decimal_places=0, max_digits=5)),
                ('ProfService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfessionalServices.PServices')),
            ],
        ),
    ]
