# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-01-06 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.TextField(max_length=500)),
                ('purchases', models.IntegerField(default=0)),
                ('udPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('totalHours', models.IntegerField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Current Unavailable', 'Current Unavailable')], default='Available', max_length=20)),
            ],
        ),
    ]
